### ISSUE TITLE
fatal error reading column 'c_name'

### ISSUE THREAD

**Issue by joymon** [elastacloud/parquet-dotnet#183]
I tried to read sample files from below repo using the nuget package.1.1.0-alpha-124 
https://github.com/Parquet/parquet-compatibility/tree/master/parquet-testdata/impala
The exception I got is as follows. Anything I am missing? Any version mismatch or anything?

ParquetException - {"fatal error reading column 'c_name'"}

Inner exception - Index was outside the bounds of the array.
   at Parquet.File.Values.RunLengthBitPackingHybridValuesReader.ReadBitpacked(Int32 header, BinaryReader reader, Int32 bitWidth, List`1 destination)
   at Parquet.File.Values.RunLengthBitPackingHybridValuesReader.ReadRleBitpackedHybrid(BinaryReader reader, Int32 bitWidth, Int32 length, List`1 destination, Int64 maxValues)
   at Parquet.File.Values.PlainDictionaryValuesReader.Read(BinaryReader reader, SchemaElement schema, IList destination, Int64 maxValues)
   at Parquet.File.PColumn.ReadColumnValues(BinaryReader reader, Encoding encoding, IList destination, Int64 maxValues)
   at Parquet.File.PColumn.ReadDataPage(PageHeader ph, IList destination, Int64 maxValues)
   at Parquet.File.PColumn.Read(String columnName, Int64 offset, Int64 count)
   at Parquet.ParquetReader.Read()

**Comment by aloneguid** [comment]
@joymon thanks for reporting this, I can confirm it's a bug and can see where it fails.

**Comment by aloneguid** [comment]
@joymon this is partially fixed, one of the files is still failing so we'll keep digging )

**Comment by aloneguid** [comment]
@joymon latest alpha includes a fix for this, let me know if you have any issues.
