### ISSUE TITLE
NullRefrenceException for IsNullable field

### ISSUE THREAD

**Issue by kRaBby** [elastacloud/parquet-dotnet#196]
Version: 1.1.128
Code:

            var ds = new DataSet(
                new SchemaElement<int>("id") ,
                new SchemaElement<int>("city") { IsNullable = true}
            );

            ds.Add(0, null);

            using (Stream fileStream = File.OpenWrite("c:\\test.parquet"))
            {
                using (var writer = new ParquetWriter(fileStream))
                {
                    writer.Write(ds);
                }
            }

StackTrace:
`
   at Parquet.File.Values.RunLengthBitPackingHybridValuesWriter.WriteData(BinaryWriter writer, List 1 data, Int32 bitWidth)
   at Parquet.File.Values.PlainDictionaryValuesWriter.Write(BinaryWriter writer, SchemaElement schema, IList data, IList& extraValues)
   at Parquet.ParquetWriter.WriteValues(SchemaElement schema, IList values, PageHeader ph, CompressionMethod compression, ColumnStats stats)
   at Parquet.ParquetWriter.Write(SchemaElement schema, IList values, CompressionMethod compression, ColumnStats stats)
   at Parquet.ParquetWriter.<>c__DisplayClass11_0.<Write>b__0(SchemaElement c)
   at System.Linq.Enumerable.WhereSelectListIterator 2.MoveNext()
   at System.Collections.Generic.List 1..ctor(IEnumerable 1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable 1 source)
   at Parquet.ParquetWriter.Write(DataSet dataSet, CompressionMethod compression, Boolean append)
`

**Comment by aloneguid** [comment]
@kRaBby it's a bug in a sense that IsNullable shouldn't be settable in schema. All fields support null values. Does it work for you when not specifying IsNullable?

**Comment by kRaBby** [comment]
No, same situation with:
`
            var ds = new DataSet(
                new SchemaElement<int>("id") ,
                new SchemaElement<int>("city")
            );

            ds.Add(0, 0);
`

**Comment by aloneguid** [comment]
@kRaBby we're looking at it, thanks for reporting.

**Comment by aloneguid** [comment]
@kRaBby we've fixed this in latest alpha, can you please try if this works for you?

**Comment by kRaBby** [comment]
It works. Thanks.
