### ISSUE TITLE
Failed deserialize parquet file

### ISSUE THREAD

**Issue by kRaBby** [elastacloud/parquet-dotnet#240]
[1.zip](https://github.com/elastacloud/parquet-dotnet/files/1381960/1.zip)

Using parquet-dotnet we serialize data.
But both Impala and parq tool cant deserialize it
To test it manually we use this code:
`ParquetReader.ReadFile(@"d:\1\1.parquet ");`

Index was outside the bounds of the array.
StackTrace:
`   at Parquet.File.Values.PlainValuesReader.ReadPlainBoolean(Byte[] data, IList destination, Int64 maxValues) in \Source\Repos\parquet-dotnet\src\Parquet\File\Values\PlainValuesReader.cs:line 74
   at Parquet.File.Values.PlainValuesReader.Read(BinaryReader reader, SchemaElement schema, IList destination, Int64 maxValues) in \Source\Repos\parquet-dotnet\src\Parquet\File\Values\PlainValuesReader.cs:line 35
   at Parquet.File.PColumn.ReadColumnValues(BinaryReader reader, Encoding encoding, IList destination, Int64 maxValues) in \Source\Repos\parquet-dotnet\src\Parquet\File\PColumn.cs:line 225
   at Parquet.File.PColumn.ReadDataPage(PageHeader ph, IList destination, Int64 maxValues) in \Source\Repos\parquet-dotnet\src\Parquet\File\PColumn.cs:line 177
   at Parquet.File.PColumn.Read(Int64 offset, Int64 count) in \Source\Repos\parquet-dotnet\src\Parquet\File\PColumn.cs:line 70
   at Parquet.ParquetReader.Read() in \Source\Repos\parquet-dotnet\src\Parquet\ParquetReader.cs:line 146`

**Comment by aloneguid** [comment]
thanks @kRaBby we'll investigate this

**Comment by aloneguid** [comment]
This was a bug in our implementation, failing when a file does not contain enough data when all values are null, all fixed in latest alpha.

**Comment by kRaBby** [comment]
great news. thanks a lot
