### ISSUE TITLE
nulable Decimal column Type_length issue

### ISSUE THREAD

**Issue by kRaBby** [elastacloud/parquet-dotnet#241]
![screenshot_2](https://user-images.githubusercontent.com/3025564/31540298-f586ceee-b013-11e7-94cc-00d52ac4fd40.png)

We have nullable decimal column. All values are null. In that case type_legth is not set and Impala fails to read. Posible this can be with other types.

From Impala source code: 
![image](https://user-images.githubusercontent.com/3025564/31541572-c8f31366-b017-11e7-839d-949fdcbc07a2.png)
http://impala.io/doc/html/hdfs-parquet-scanner_8cc_source.html

**Comment by kRaBby** [comment]
this issue related to https://github.com/elastacloud/parquet-dotnet/issues/243

**Comment by kRaBby** [comment]
It looks like it not related with https://github.com/elastacloud/parquet-dotnet/issues/243
After last update (1.4.0-alpha-157) I catched this:
`
hadoop jar parquet-tools-1.9.0.jar schema --debug <file>
java.lang.IllegalArgumentException: Invalid FIXED_LEN_BYTE_ARRAY length: 0
        at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:55)
        at org.apache.parquet.schema.Types$BasePrimitiveBuilder.build(Types.java:380)
        at org.apache.parquet.schema.Types$BasePrimitiveBuilder.build(Types.java:307)
        at org.apache.parquet.schema.Types$Builder.named(Types.java:288)
        at org.apache.parquet.format.converter.ParquetMetadataConverter.buildChildren(ParquetMetadataConverter.java:901)
        at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetSchema(ParquetMetadataConverter.java:862)
        at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetMetadata(ParquetMetadataConverter.java:799)
        at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:793)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:502)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:461)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:417)
        at org.apache.parquet.tools.command.ShowSchemaCommand.execute(ShowSchemaCommand.java:93)
        at org.apache.parquet.tools.Main.main(Main.java:223)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Invalid FIXED_LEN_BYTE_ARRAY length: 0
`
And I cant check for what exact column this exception.
It looks like now for nulable decimal column with all values null legth is set but zero.

**Comment by aloneguid** [comment]
@kRaBby this is still an issue, we'll have to check what parquet-mr does in this case, parquet spec doesn't say anything about it, so it's a matter of making other parsers happy. Bear with me, the fix is coming.

**Comment by aloneguid** [comment]
Writing a null column in Scala just stamps it with default type length (38, 18) let me try to put this fix in

![image](https://user-images.githubusercontent.com/3155189/31715834-3d111a70-b3fd-11e7-8a20-df212a7ffd20.png)

**Comment by aloneguid** [comment]
@kRaBby all good now, published to latest alpha, both Impala and Spark understands columns with all nulls. Can you validate it works for you?

**Comment by kRaBby** [comment]
Looks like still something wrong:
`File '...' column '...' has an invalid type length. Expecting: 8 len in file: 16`

**Comment by aloneguid** [comment]
@kRaBby how do you end up with this file, can you provide a code sample?

**Comment by aloneguid** [comment]
@kRaBby any update on this?

**Comment by kRaBby** [comment]
Sorry for a long time did not answer.
With old version (1.3) I can not reproduce it in test. But with new version (1.5) I have exception:
Value cannot be null.
Parameter name: item
`   at System.ThrowHelper.IfNullAndNullsAreIllegalThenThrow[T](Object value, ExceptionArgument argName)
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at Parquet.Data.DataSet.AddRow(Row row, IList`1 schema, Boolean updateCount)
   at Parquet.Data.DataSet.AddRow(Row row)
   at Parquet.Data.DataSet.Add(Row item)
`
Can you fix it? And I will try to rerpoduce nulable Decimal again.

**Comment by aloneguid** [comment]
@kRaBby there is a breaking change in 1.4 and up on defining nullable schemas https://github.com/elastacloud/parquet-dotnet/releases - essentially now you need to define schema as `SchemaElement<decimal?>`.

**Comment by kRaBby** [comment]
In case of SchemaElement<decimal?> how can I setup precision and scale?

**Comment by kRaBby** [comment]
Look, I have made some changes and it looks good.
DecimalSchemaElement.cs
I added to ctor param 
`bool nullable = false` 
and
`Thrift.Repetition_type = nullable ? FieldRepetitionType.OPTIONAL : FieldRepetitionType.REQUIRED;`
Also I'm not sure about necessity to call `UpdateFlags();` or something else from base class.

Usage. 
Instead of SchemaElement<decimal> or SchemaElement<decimal?> I used DecimalSchemaElement(name, pr, sc, true, true/false).

After that completly empty decimal? column has right Type_length.

**Comment by aloneguid** [comment]
Hey @kRaBby yes you're right, forgot to account for nulls in DSE. Are you OK to raise a PR for this?

**Comment by kRaBby** [comment]
@aloneguid  Yes, sure. And what about:
> Also I'm not sure about necessity to call UpdateFlags(); or something else from base class.
Should I add it?

**Comment by aloneguid** [comment]
@kRaBby ah yes sorry, `UpdateFlags()` is called from base - `: base(name)` however it sets the schema to required. I think you may need to pass the `nullable` Boolean down to `Builder.CreateSimpleSchemaElement`:

```csharp
      protected SchemaElement(string name) : this()
      {
         Name = name ?? throw new ArgumentNullException(nameof(name));
         Thrift = Builder.CreateSimpleSchemaElement(name); // <--- here

         UpdateFlags();
      }
```
