### ISSUE TITLE
Tests that rely on CSV file comparison fails in locales with commas reversed

### ISSUE THREAD

**Issue by slogen** [elastacloud/parquet-dotnet#322]
**Version:** Parquet.Net v2.1 (and git, master 0a153b092040ccaa7de001daf2cb2ed1b09e2d0d)

**Runtime Version:** N/A

**OS:** N/A

#### Expected behavior

I expected all Unit tests to pass. 

#### Actual behavior

All 7 Unit tests in  Parquet.Test.Reader.TestDataTest all fail due to the same locale-dependent CSV parsing issue.

The applied parsing is not valid in all locales, as some locales have inverted the meaning of "." and ",", as compared to en-US. This specifically happens in my locale (da-DK).

The CSV parser is not immediately fixable (uses Netbox and has no options for specifying the locale to parse). 

Six tests fails with the same message as `Alltypes_dictionary_gzipped`:

```
Test Name:	Parquet.Test.Reader.TestDataTest.Alltypes_dictionary_gzipped
Test FullName:	Parquet.Test.Reader.TestDataTest.Alltypes_dictionary_gzipped
Test Source:	C:\Users\hej\source\repos\parquet-dotnet\src\Parquet.Test\Reader\TestDataTest.cs : line 125
Test Outcome:	Failed
Test Duration:	0:00:00,159

Result StackTrace:	
at Parquet.Test.Reader.ParquetCsvComparison.Compare(DataColumn[] parquet, DataColumn[] csv, Type[] columnTypes) in C:\Users\hej\source\repos\parquet-dotnet\src\Parquet.Test\Reader\ParquetCsvComparison.cs:line 67
   at Parquet.Test.Reader.ParquetCsvComparison.CompareFiles(String baseName, String encoding, Type[] columnTypes) in C:\Users\hej\source\repos\parquet-dotnet\src\Parquet.Test\Reader\ParquetCsvComparison.cs:line 23
   at Parquet.Test.Reader.TestDataTest.Alltypes_dictionary_gzipped() in C:\Users\hej\source\repos\parquet-dotnet\src\Parquet.Test\Reader\TestDataTest.cs:line 127
Result Message:	
expected 11 but was 1,1 in column float_col, value #1
Expected: True
Actual:   False
```
`Parquet.Test.Reader.TestDataTest.Postcodes_sample_no_compression` fails with

```
Test Name:	Parquet.Test.Reader.TestDataTest.Postcodes_sample_no_compression
Test FullName:	Parquet.Test.Reader.TestDataTest.Postcodes_sample_no_compression
Test Source:	C:\Users\hej\source\repos\parquet-dotnet\src\Parquet.Test\Reader\TestDataTest.cs : line 143
Test Outcome:	Failed
Test Duration:	0:00:00,009

Result StackTrace:	
at Parquet.Test.Reader.ParquetCsvComparison.Compare(DataColumn[] parquet, DataColumn[] csv, Type[] columnTypes) in C:\Users\hej\source\repos\parquet-dotnet\src\Parquet.Test\Reader\ParquetCsvComparison.cs:line 67
   at Parquet.Test.Reader.ParquetCsvComparison.CompareFiles(String baseName, String encoding, Type[] columnTypes) in C:\Users\hej\source\repos\parquet-dotnet\src\Parquet.Test\Reader\ParquetCsvComparison.cs:line 23
   at Parquet.Test.Reader.TestDataTest.Postcodes_sample_no_compression() in C:\Users\hej\source\repos\parquet-dotnet\src\Parquet.Test\Reader\TestDataTest.cs:line 145
Result Message:	
expected 57119458 but was 57,119458 in column Latitude, value #0
Expected: True
Actual:   False
```

### Steps to reproduce the behavior

1. Checkout code & compile
2. Run unit-tests in locale da-DK

This can be a bit hard to do :) So I have forked and created a demo for it at https://github.com/slogen/parquet-dotnet/tree/bug/locale_dependent_csv_parsing

#### Code snippet reproducing the behavior

https://github.com/slogen/parquet-dotnet/commit/72b434b3a562eb87da8b38003c93fa7c849587ea

The demo utilizes a workaround, which is quite ugly, from https://github.com/xunit/samples.xunit/blob/master/UseCulture/UseCultureAttribute.cs.

- [ ] I'm attaching a sample .parquet file containing the problem.
- [x] I am happy to contribute to this repository by fixing this issue and raising a Pull Request (see [contribution guide](CONTRIBUTING.md))

**Comment by aloneguid** [comment]
@slogen thanks for reporting this. I agree the parsing could be better, either better parsing or culture workaround should be added. Are you happy to raise a PR?

**Comment by aloneguid** [comment]
@slogen thank you for contributing, looks good and all merged.
