### ISSUE TITLE
version 3.2.4: Exception opening some files

### ISSUE THREAD

**Issue by theconnectionist** [elastacloud/parquet-dotnet#382]
I recently started working with [CommonCrawl parquet streams](https://commoncrawl.s3.amazonaws.com/cc-index/table/cc-main/index.html). I started with 3.2.3 and was able to rip through all 300 files and open a few columns and process them without any problem. After upgrading to 3.2.4, reprocessing the same files, I run into this exception for a couple of columns (url_query and content_languages). Is this a known problem?

I reverted back to 3.2.3 and am able to process without an issue. The only commonality between these two streams is they are Nullable, but then again I had no problem processing another nullable column.

The data files are too large to share/upload, but can be downloaded using instructions [here](https://github.com/commoncrawl/cc-index-table/issues/1). I'll try to debug the issue, but hoping this is easily reproducible or already known to be a problem.

```
Exception: Index was outside the bounds of the array.. Stack:    at Parquet.File.Values.RunLengthBitPackingHybridValuesReader.ReadRle(Int32 header, BinaryReader reader, Int32 bitWidth, Int32[] dest, Int32 offset)
   at Parquet.File.Values.RunLengthBitPackingHybridValuesReader.ReadRleBitpackedHybrid(BinaryReader reader, Int32 bitWidth, Int32 length, Int32[] dest, Int32 offset)
   at Parquet.File.DataColumnReader.ReadDataPage(PageHeader ph, ColumnRawData cd, Int64 maxValues)
   at Parquet.File.DataColumnReader.Read()
   at Parquet.ParquetRowGroupReader.ReadColumn(DataField field)
```

**Comment by mmolaro** [comment]
Can confirm there is an issue with 3.2.4. The `parq` command line tool also suffers from this. parq 3.2.4 fails at opening some larger files that parq 3.2.2 has no problem opening for viewing and converting to json representation.

**Comment by theconnectionist** [comment]
@mmolaro thanks for the confirmation. I'm following up on this issue in the comment section of the [commit](https://github.com/elastacloud/parquet-dotnet/commit/42317e54a1764f10693d68692cd7d1d3d0298e33?_pjax=%23js-repo-pjax-container) which introduced this fix.

**Comment by mgolen** [comment]
Hi everyone,

I think I've got similar issue.
When I try to read attached file using either example code from https://github.com/elastacloud/parquet-dotnet#reading-files or by using parq, then IndexOutOfRangeException is thrown with below stacktrace:

>    System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Parquet.File.Values.RunLengthBitPackingHybridValuesReader.ReadRle(Int32 header, BinaryReader reader, Int32 bitWidth, Int32[] dest, Int32 offset) in D:\a\1\s\src\Parquet\File\Values\RunLengthBitPackingHybridValuesReader.cs:line 81
   at Parquet.File.Values.RunLengthBitPackingHybridValuesReader.ReadRleBitpackedHybrid(BinaryReader reader, Int32 bitWidth, Int32 length, Int32[] dest, Int32 offset) in D:\a\1\s\src\Parquet\File\Values\RunLengthBitPackingHybridValuesReader.cs:line 46
   at Parquet.File.DataColumnReader.ReadDataPage(PageHeader ph, ColumnRawData cd, Int64 maxValues) in D:\a\1\s\src\Parquet\File\DataColumnReader.cs:line 191
   at Parquet.File.DataColumnReader.Read() in D:\a\1\s\src\Parquet\File\DataColumnReader.cs:line 92
   at Parquet.ParquetRowGroupReader.ReadColumn(DataField field) in D:\a\1\s\src\Parquet\ParquetRowGroupReader.cs:line 64

When I downgrade to 3.2.3, then exception is not thrown.
I'm using .NET Core 2.1.403 on Windows 10x64 build 1709.

May I ask for confirmation if attached parquet file is correct and it is indeed the same issue?
Thanks in advance.

Attached file:
[test.zip](https://github.com/elastacloud/parquet-dotnet/files/2731942/test.zip)

**Comment by aloneguid** [comment]
I can reproduce this issue too, let me try something first.

**Comment by aloneguid** [comment]
Can you try v3.3.2 on nuget please? I've added some extra check on RLE array boundaries and both parq and library are reading the file for me. It seems like there is a tail of bytes in the file library is trying to read, although they don't carry any data.

**Comment by mgolen** [comment]
I've updated both NuGet package in my project and parq to version 3.3.2. IndexOutOfRangeException is not thrown in both cases. It looks like that extra check did the trick. Thank you!

**Comment by aloneguid** [comment]
Happy to help!
