### ISSUE TITLE
Cannot write (and read?) empty tables (in old version 2.1.4 it was possible)

### ISSUE THREAD

**Issue by kirchsth** [elastacloud/parquet-dotnet#423]
**Version:** Parquet.Net v 3.3.5

**Runtime Version:** .Net Framework v 4.7.2

**OS:** Windows 10

#### Expected behavior

Parquet.Net can write/read empty parquet files like in the old 2.1.4 version (via DataSets)

#### Actual behavior

**writer.Write(table);** creates an KeyNotFoundException if the table is empty

with following stack
```
System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Parquet.Data.Rows.RowsToDataColumnsConverter.<Convert>b__4_0(DataField df) in /home/vsts/work/1/s/src/Parquet/Data/Rows/RowsToDataColumnsConverter.cs:line 25
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Parquet.Data.Rows.RowsToDataColumnsConverter.Convert() in /home/vsts/work/1/s/src/Parquet/Data/Rows/RowsToDataColumnsConverter.cs:line 28
   at Parquet.ParquetExtensions.Write(ParquetRowGroupWriter writer, Table table) in /home/vsts/work/1/s/src/Parquet/ParquetExtensions.cs:line 111
   at Parquet.ParquetExtensions.Write(ParquetWriter writer, Table table) in /home/vsts/work/1/s/src/Parquet/ParquetExtensions.cs:line 66
   at ****.ParquetTests.Array_write_read() in  ***** 
```

### Steps to reproduce the behavior

1. Run the unit test with the (uncommented) table.Add() calls the test is green 
2. Run the unit test without the (commented) table.Add() calls the test fails 

#### Code snippet reproducing the behavior

it is basically the already existing Array_write_read() unit test. I commented only the add calls (and use a NUnit test framework)

```csharp
        [Test(Description = "check if parquet 3.x can write empty tables at all")]
        // [Fact]
        public void Array_write_read()
        {
            var table = new Table(
                new Schema(
                    new DataField<int>("id"),
                    new DataField<string[]>("categories")     //array field
                )
            );

            var ms = new MemoryStream();

            // table.Add(1, new[] { "1", "2", "3" });
            // table.Add(3, new[] { "3", "3", "3" });

            //write to stream
            using (var writer = new ParquetWriter(table.Schema, ms))
            {
                writer.Write(table);
            }

            //System.IO.File.WriteAllBytes("c:\\tmp\\1.parquet", ms.ToArray());

            //read back into table
            ms.Position = 0;

            Table table2;
            using (var reader = new ParquetReader(ms))
            {
                table2 = reader.ReadAsTable();
            }

            //validate data
            // Assert.Equal(table.ToString(), table2.ToString(), ignoreLineEndingDifferences: true);
            table.ToString().Replace("\r","").Replace("\n","").Should().
                Be(table2.ToString().Replace("\r","").Replace("\n",""));
        }

```

**Comment by aloneguid** [comment]
fixed

**Comment by kirchsth** [comment]
thank you, Helmut
